"""
build_stubs.py — Generate stub_decks.py from real decklists in meta-analyzer DB.
Run once to regenerate; commit the output.
"""
import sys, os, json, sqlite3
sys.path.insert(0, '.')

DB = os.path.join('..', 'mtg-meta-analyzer', 'data', 'mtg_meta.db')
conn = sqlite3.connect(DB)
cur  = conn.cursor()

cur.execute("SELECT id, name, format, archetype, mainboard FROM saved_decks ORDER BY id")
rows = cur.fetchall()
conn.close()

lines = ['"""',
         'data/stub_decks.py — Real decklists from mtg-meta-analyzer DB.',
         'Auto-generated by build_stubs.py. Re-run to update.',
         '"""',
         'import sys, os',
         'sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))',
         '',
         '_DB_DECKS = {',
         ]

for did, name, fmt, arch, mb_json in rows:
    mb = json.loads(mb_json)
    safe = name.lower().replace(' ','_').replace("'","").replace('/','_')
    lines.append(f'    # {name} ({fmt})')
    lines.append(f'    "{safe}": {{')
    lines.append(f'        "format": "{fmt}",')
    lines.append(f'        "mainboard": {json.dumps(mb, indent=8)},')
    lines.append('    },')

lines += [
    '}',
    '',
    '',
    'def get_stub_deck_list(deck_name: str) -> dict | None:',
    '    """Return {card_name: qty} mainboard dict for a named deck."""',
    '    key = deck_name.lower().replace(" ","_").replace("\'","").replace("/","_")',
    '    # Exact match',
    '    if key in _DB_DECKS:',
    '        return _DB_DECKS[key]["mainboard"]',
    '    # Partial match on archetype name',
    '    for k, v in _DB_DECKS.items():',
    '        if key in k or k in key:',
    '            return v["mainboard"]',
    '    return None',
    '',
    '',
    'def get_format_decks(format_name: str) -> dict:',
    '    """Return all decks for a given format."""',
    '    return {k: v for k, v in _DB_DECKS.items()',
    '            if v["format"] == format_name}',
]

out = '\n'.join(lines)
with open('data/stub_decks.py', 'w') as f:
    f.write(out)
print(f"Generated data/stub_decks.py with {len(rows)} decks")
