"""Every rule engine v2 relies on, with verbatim quotations from the pinned CR
(MagicCompRules-20260925.txt). test_rule_citations checks each quotation is a
substring of its OWN numbered entry. Where an implementation cites a rule, it
cites one of these ids."""

CITATIONS = {
    "103.5": ["the starting player declares whether they will take a mulligan",
              "puts a number of those cards equal to the number of times that player has taken a mulligan on the bottom of their library in any order",
              "A player can take mulligans until their opening hand would be zero cards"],
    "103.3": ["each player shuffles their deck"],
    "103.4": ["Each player begins the game with a starting life total of 20."],
    "103.8a": ["the player who plays first skips the draw step"],
    "104.4a": ["If all the players remaining in a game lose simultaneously, the game is a draw."],
    "106.4": ["empties at the end of each step and phase"],
    "110.2": ["the player under whose control it entered the battlefield"],
    "115.5": ["A spell or ability on the stack is an illegal target for itself."],
    "117.3a": ["No player receives priority during the untap step."],
    "117.3b": ["The active player receives priority after a spell or ability (other than a mana ability) resolves."],
    "117.3c": ["that player receives priority afterward"],
    "117.4": ["if the stack is empty, the phase or step ends"],
    "117.5": ["the game first performs all applicable state-based actions as a single event"],
    "302.6": ["continuously since their most recent turn began"],
    "305.2": ["A player can normally play one land during their turn"],
    "307.1": ["during a main phase of their turn when the stack is empty"],
    "400.7": ["becomes a new object with no memory of, or relation to, its previous existence"],
    "500.5": ["Then any unspent mana left in a player"],
    "502.3": ["Then they untap them all simultaneously."],
    "504.1": ["First, the active player draws a card."],
    "508.1a": ["each one must either have haste or have been controlled by the active player continuously since the turn began"],
    "508.1f": ["The active player taps the chosen creatures."],
    "508.8": ["skip the declare blockers and combat damage steps"],
    "509.1a": ["The chosen creatures must be untapped"],
    "510.1c": ["it assigns its combat damage to those creatures divided as its controller chooses among them"],
    "510.2": ["is dealt simultaneously"],
    "510.4": ["the only creatures that assign combat damage in that step are those with first strike or double strike"],
    "514.1": ["they discard enough cards to reduce their hand size to that number"],
    "514.2": ["all damage marked on permanents (including phased-out permanents) is removed"],
    "601.2": ["To cast a spell is to take it from where it is (usually the hand), put it on the stack, and pay its costs"],
    "601.2a": ["a player first moves that card (or that copy of a card) from where it is to the stack"],
    "601.2c": ["The player announces their choice of an appropriate object or player for each target the spell requires."],
    "601.2g": ["Mana abilities must be activated before costs are paid."],
    "601.2h": ["Partial payments are not allowed."],
    "601.2i": ["then the spell becomes cast"],
    "605.3a": ["A player may activate an activated mana ability whenever they have priority"],
    "608.2b": ["no longer in the zone it was in when it was targeted is illegal"],
    "608.2n": ["As the final part of an instant or sorcery spell"],
    "608.3a": ["it becomes a permanent and enters the battlefield under the control of the spell"],
    "701.6a": ["A countered spell is put into its owner"],
    "702.7b": ["the only creatures that assign combat damage in that step are those with first strike or double strike"],
    "702.9b": ["except by creatures with flying and/or reach"],
    "702.10b": ["If a creature has haste, it can attack even if it hasn"],
    "702.20b": ["cause creatures with vigilance to tap"],
    "704.5a": ["If a player has 0 or less life, that player loses the game."],
    "704.5b": ["attempted to draw a card from a library with no cards in it since the last time state-based actions were checked"],
    "704.5f": ["If a creature has toughness 0 or less"],
    "704.5g": ["that creature has been dealt lethal damage and is destroyed"],
    "733.1": ["the entire action is reversed and any payments already made are canceled",
              "If the action was casting a spell, the spell returns to the zone it came from.",
              "Each player may also reverse any legal mana abilities that player activated while making the illegal play"],
    "733.2": ["the player who had priority retains it"],
    "119.3": ["If an effect causes a player to gain life or lose life, that player’s life total is adjusted accordingly."],
    "115.1": ["Some spells and abilities require their controller to choose one or more targets for them."],
    "120.3": ["Damage may have one or more of the following results"],
    "120.3a": ["Damage dealt to a player by a source without infect causes that player to lose that much life."],
    "205.3k": ["The spell types are Adventure, Arcane, Lesson, Omen, and Trap."],
    "503.1a": ['Any abilities that triggered during the untap step and any abilities that triggered at the beginning of the upkeep are put onto the stack before the active play'],
    "508.1": ['First, the active player declares attackers.'],
    "601.2b": ['If the spell is modal, the player announces the mode choice (see rule 700.2).'],
    "602.2a": ['The player announces that they are activating the ability.'],
    "603.2": ['Whenever a game event or game state matches a triggered ability’s trigger event, that ability automatically triggers.'],
    "603.3": ['Once an ability has triggered, its controller puts it on the stack as an object that’s not a card the next time a player would receive priority.'],
    "603.3a": ['A triggered ability is controlled by the player who controlled its source at the time it triggered, unless it’s a delayed triggered ability.'],
    "603.3b": ['If multiple abilities have triggered since the last time a player received priority, the abilities are placed on the stack in a two-part process.'],
    "603.3d": ['The remainder of the process for putting a triggered ability on the stack is identical to the process for casting a spell listed in rules 601.2c–d.'],
    "603.4": ['A triggered ability may read “When/Whenever/At [trigger event], if [condition], [effect].” When the trigger event occurs, the ability checks whether the stated '],
    "609.3": ['If an effect attempts to do something impossible, it does only as much as possible.'],
    "614.12": ['Some replacement effects modify how a permanent enters the battlefield.'],
    "700.2a": ['The controller of a modal spell or activated ability chooses the mode(s) as part of casting that spell or activating that ability.'],
    "701.20a": ['To reveal a card, show that card to all players for a brief time.'],
    "702.108a": ['Prowess is a triggered ability.'],
    "702.137a": ['Spectacle is a static ability that functions on the stack.'],
    "701.20b": ['Revealing a card doesn’t cause it to leave the zone it’s in.'],
    "702.108b": ['If a creature has multiple instances of prowess, each triggers separately.'],
    "113.7a": ['Once activated or triggered, an ability exists on the stack independently of its source.'],
    "118.3": ['A player can’t pay a cost without having the necessary resources to pay it fully.'],
    "119.4": ['If a cost or effect allows a player to pay an amount of life greater than 0, the player may do so only if their life total is greater than or equal to the amoun'],
    "305.6": ['The basic land types are Plains, Island, Swamp, Mountain, and Forest.'],
    "602.2": ['To activate an ability is to put it onto the stack and pay its costs, so that it will eventually resolve and have its effect.'],
    "605.3b": ['An activated mana ability doesn’t go on the stack, so it can’t be targeted, countered, or otherwise responded to.'],
    "614.1c": ['Effects that read “[This permanent] enters with .'],
    "614.1d": ['Continuous effects that read “[This permanent] enters .'],
    "608.2": ['If the object that’s resolving is an instant spell, a sorcery spell, or an ability, its resolution may involve several steps.'],
    "701.23": ['Search'],
    "701.23a": ['To search for a card in a zone, look at all cards in that zone (even if it’s a hidden zone) and find a card that matches the given description.'],
    "701.23b": ['If a player is searching a hidden zone for cards with a stated quality, such as a card with a certain card type or color, that player isn’t required to find som'],
    "119.7": ['If an effect says that a player can’t gain life, that player can’t make an exchange such that the player’s life total would become higher; in that case, the exc'],
    "615.12": ['Some effects state that damage “can’t be prevented.” If unpreventable damage would be dealt, any applicable prevention effects are still applied to it.'],
    "702.12b": ['A permanent with indestructible can’t be destroyed.'],
    "702.4b": ['If at least one attacking or blocking creature has first strike (see rule 702.7) or double strike as the combat damage step begins, the only creatures that assi'],
    "611.2c": ['If a continuous effect generated by the resolution of a spell or ability modifies the characteristics or changes the controller of any objects, the set of objec'],
    "116.2f": ['A player who has a card with suspend in their hand may exile that card.'],
    "118.9": ['Some spells have alternative costs.'],
    "601.2f": ['The player determines the total cost of the spell.'],
    "608.2g": ['If an effect gives a player the option to pay mana, they may activate mana abilities before taking that action.'],
    "702.62a": ['Suspend is a keyword that represents three abilities.'],
    "702.62c": ['While determining if you could begin to cast a card with suspend, take into consideration any effects that would prohibit that card from being cast.'],
    "100.2a": ['In constructed play (a way of playing in which each player creates their own deck ahead of time), each deck has a minimum deck size of 60 cards.'],
    "100.4": ['Each player may also have a sideboard, which is a group of additional cards the player may use to modify their deck between games of a match.'],
    "103.1": ['At the start of a game, the players determine which one of them will choose who takes the first turn.'],
    "107.4f": ['can be paid either with one mana of its color or by paying 2 life'],
    "111.1": ['A token is a marker used to represent any permanent'],
    "111.7": ['This is a state-based action; see rule 704.'],
    "116.2k": ['This is a special action.'],
    "205.2a": ['The card types are artifact, battle, conspiracy, creature'],
    "207.2c": ['An ability word appears in italics at the beginning of some abilities.'],
    "301.5a": ['The creature an Equipment is attached to is called the'],
    "301.5c": ['An Equipment that equips an illegal or nonexistent permanent becomes unattached from that permanent but remains on the battlefield.'],
    "305.1": ['may play a land card from their hand during a main phase of their turn when the stack is empty'],
    "404.2": ['Each graveyard is kept in a single face-up pile.'],
    "508.1d": ['effects that say a creature attacks if able'],
    "601.3": ['A player can begin to cast a spell only if a rule or effect allows that player to cast it'],
    "602.2b": ['Those rules apply to activating an ability just as they apply to casting a spell.'],
    "602.5d": ['mean the player must follow the timing rules for casting a sorcery spell'],
    "603.7": ['An effect may create a delayed triggered ability that can do something at a later time.'],
    "603.7a": ['Delayed triggered abilities are created during the resolution of spells or abilities'],
    "603.7b": ['A delayed triggered ability will trigger only once'],
    "603.7e": ['If an activated or triggered ability creates a delayed triggered ability, the source of that delayed triggered ability is the same as the source of that other a'],
    "611.3a": ['it applies at any given moment to whatever its text indicates'],
    "613.1": ['are determined by starting with the actual object'],
    "701.22a": ['put any number of them on the bottom of your library in any order and the rest on top of your library in any order'],
    "701.22b": ['no scry event occurs'],
    "701.25a": ['put any number of them into your graveyard and the rest on top of your library in any order'],
    "701.3a": ['means to take it from where it currently is and put it onto that object or player'],
    "701.3b": ['the effect does nothing'],
    "702.170": ['Plot'],
    "702.170a": ['Any time you have priority during your main phase while the stack is empty'],
    "702.170d": ['during their main phase while the stack is empty during any turn after the turn in which it became plotted'],
    "702.19b": ['Once all those blocking creatures are assigned lethal damage, any excess damage is assigned as its controller chooses'],
    "702.19d": ['its damage is assigned to the defending player and/or planeswalker as though all blocking creatures have been assigned lethal damage'],
    "702.34a": ['exile this card instead of putting it anywhere else any time it would leave the stack'],
    "702.6a": ['Attach this permanent to target creature you control. Activate only as a sorcery.'],
    "704.5d": ['If a token is in a zone other than the battlefield, it ceases to exist.'],
    "704.5n": ['It remains on the battlefield.'],
}
