"""Every rule engine v2 relies on, with verbatim quotations from the pinned CR
(MagicCompRules-20260925.txt). test_rule_citations checks each quotation is a
substring of its OWN numbered entry. Where an implementation cites a rule, it
cites one of these ids."""

CITATIONS = {
    "103.5": ["the starting player declares whether they will take a mulligan",
              "puts a number of those cards equal to the number of times that player has taken a mulligan on the bottom of their library in any order",
              "A player can take mulligans until their opening hand would be zero cards"],
    "103.3": ["each player shuffles their deck"],
    "103.4": ["Each player begins the game with a starting life total of 20."],
    "103.8a": ["the player who plays first skips the draw step"],
    "104.4a": ["If all the players remaining in a game lose simultaneously, the game is a draw."],
    "106.4": ["empties at the end of each step and phase"],
    "110.2": ["the player under whose control it entered the battlefield"],
    "115.5": ["A spell or ability on the stack is an illegal target for itself."],
    "117.3a": ["No player receives priority during the untap step."],
    "117.3b": ["The active player receives priority after a spell or ability (other than a mana ability) resolves."],
    "117.3c": ["that player receives priority afterward"],
    "117.4": ["if the stack is empty, the phase or step ends"],
    "117.5": ["the game first performs all applicable state-based actions as a single event"],
    "302.6": ["continuously since their most recent turn began"],
    "305.2": ["A player can normally play one land during their turn"],
    "307.1": ["during a main phase of their turn when the stack is empty"],
    "400.7": ["becomes a new object with no memory of, or relation to, its previous existence"],
    "500.5": ["Then any unspent mana left in a player"],
    "502.3": ["Then they untap them all simultaneously."],
    "504.1": ["First, the active player draws a card."],
    "508.1a": ["each one must either have haste or have been controlled by the active player continuously since the turn began"],
    "508.1f": ["The active player taps the chosen creatures."],
    "508.8": ["skip the declare blockers and combat damage steps"],
    "509.1a": ["The chosen creatures must be untapped"],
    "510.1c": ["it assigns its combat damage to those creatures divided as its controller chooses among them"],
    "510.2": ["is dealt simultaneously"],
    "510.4": ["the only creatures that assign combat damage in that step are those with first strike or double strike"],
    "514.1": ["they discard enough cards to reduce their hand size to that number"],
    "514.2": ["all damage marked on permanents (including phased-out permanents) is removed"],
    "601.2": ["To cast a spell is to take it from where it is (usually the hand), put it on the stack, and pay its costs"],
    "601.2a": ["a player first moves that card (or that copy of a card) from where it is to the stack"],
    "601.2c": ["The player announces their choice of an appropriate object or player for each target the spell requires."],
    "601.2g": ["Mana abilities must be activated before costs are paid."],
    "601.2h": ["Partial payments are not allowed."],
    "601.2i": ["then the spell becomes cast"],
    "605.3a": ["A player may activate an activated mana ability whenever they have priority"],
    "608.2b": ["no longer in the zone it was in when it was targeted is illegal"],
    "608.2n": ["As the final part of an instant or sorcery spell"],
    "608.3a": ["it becomes a permanent and enters the battlefield under the control of the spell"],
    "701.6a": ["A countered spell is put into its owner"],
    "702.7b": ["the only creatures that assign combat damage in that step are those with first strike or double strike"],
    "702.9b": ["except by creatures with flying and/or reach"],
    "702.10b": ["If a creature has haste, it can attack even if it hasn"],
    "702.20b": ["cause creatures with vigilance to tap"],
    "704.5a": ["If a player has 0 or less life, that player loses the game."],
    "704.5b": ["attempted to draw a card from a library with no cards in it since the last time state-based actions were checked"],
    "704.5f": ["If a creature has toughness 0 or less"],
    "704.5g": ["that creature has been dealt lethal damage and is destroyed"],
    "733.1": ["the entire action is reversed and any payments already made are canceled",
              "If the action was casting a spell, the spell returns to the zone it came from.",
              "Each player may also reverse any legal mana abilities that player activated while making the illegal play"],
    "733.2": ["the player who had priority retains it"],
    "119.3": ["If an effect causes a player to gain life or lose life, that player’s life total is adjusted accordingly."],
    "115.1": ["Some spells and abilities require their controller to choose one or more targets for them."],
    "120.3": ["Damage may have one or more of the following results"],
    "120.3a": ["Damage dealt to a player by a source without infect causes that player to lose that much life."],
    "205.3k": ["The spell types are Adventure, Arcane, Lesson, Omen, and Trap."],
    "503.1a": ['Any abilities that triggered during the untap step and any abilities that triggered at the beginning of the upkeep are put onto the stack before the active play'],
    "508.1": ['First, the active player declares attackers.'],
    "601.2b": ['If the spell is modal, the player announces the mode choice (see rule 700.2).'],
    "602.2a": ['The player announces that they are activating the ability.'],
    "603.2": ['Whenever a game event or game state matches a triggered ability’s trigger event, that ability automatically triggers.'],
    "603.3": ['Once an ability has triggered, its controller puts it on the stack as an object that’s not a card the next time a player would receive priority.'],
    "603.3a": ['A triggered ability is controlled by the player who controlled its source at the time it triggered, unless it’s a delayed triggered ability.'],
    "603.3b": ['If multiple abilities have triggered since the last time a player received priority, the abilities are placed on the stack in a two-part process.'],
    "603.3d": ['The remainder of the process for putting a triggered ability on the stack is identical to the process for casting a spell listed in rules 601.2c–d.'],
    "603.4": ['A triggered ability may read “When/Whenever/At [trigger event], if [condition], [effect].” When the trigger event occurs, the ability checks whether the stated '],
    "609.3": ['If an effect attempts to do something impossible, it does only as much as possible.'],
    "614.12": ['Some replacement effects modify how a permanent enters the battlefield.'],
    "700.2a": ['The controller of a modal spell or activated ability chooses the mode(s) as part of casting that spell or activating that ability.'],
    "701.20a": ['To reveal a card, show that card to all players for a brief time.'],
    "702.108a": ['Prowess is a triggered ability.'],
    "702.137a": ['Spectacle is a static ability that functions on the stack.'],
    "701.20b": ['Revealing a card doesn’t cause it to leave the zone it’s in.'],
    "702.108b": ['If a creature has multiple instances of prowess, each triggers separately.'],
    "113.7a": ['Once activated or triggered, an ability exists on the stack independently of its source.'],
    "118.3": ['A player can’t pay a cost without having the necessary resources to pay it fully.'],
    "119.4": ['If a cost or effect allows a player to pay an amount of life greater than 0, the player may do so only if their life total is greater than or equal to the amoun'],
    "305.6": ['The basic land types are Plains, Island, Swamp, Mountain, and Forest.'],
    "602.2": ['To activate an ability is to put it onto the stack and pay its costs, so that it will eventually resolve and have its effect.'],
    "605.3b": ['An activated mana ability doesn’t go on the stack, so it can’t be targeted, countered, or otherwise responded to.'],
    "614.1c": ['Effects that read “[This permanent] enters with .'],
    "614.1d": ['Continuous effects that read “[This permanent] enters .'],
}
