"""Every rule engine v2 relies on, with verbatim quotations from the pinned CR
(MagicCompRules-20260925.txt). test_rule_citations checks each quotation is a
substring of its OWN numbered entry. Where an implementation cites a rule, it
cites one of these ids."""

CITATIONS = {
    "103.5": ["the starting player declares whether they will take a mulligan",
              "puts a number of those cards equal to the number of times that player has taken a mulligan on the bottom of their library in any order",
              "A player can take mulligans until their opening hand would be zero cards"],
    "103.3": ["each player shuffles their deck"],
    "103.4": ["Each player begins the game with a starting life total of 20."],
    "103.8a": ["the player who plays first skips the draw step"],
    "104.4a": ["If all the players remaining in a game lose simultaneously, the game is a draw."],
    "106.4": ["empties at the end of each step and phase"],
    "110.2": ["the player under whose control it entered the battlefield"],
    "115.5": ["A spell or ability on the stack is an illegal target for itself."],
    "117.3a": ["No player receives priority during the untap step."],
    "117.3b": ["The active player receives priority after a spell or ability (other than a mana ability) resolves."],
    "117.3c": ["that player receives priority afterward"],
    "117.4": ["if the stack is empty, the phase or step ends"],
    "117.5": ["the game first performs all applicable state-based actions as a single event"],
    "302.6": ["continuously since their most recent turn began"],
    "305.2": ["A player can normally play one land during their turn"],
    "307.1": ["during a main phase of their turn when the stack is empty"],
    "400.7": ["becomes a new object with no memory of, or relation to, its previous existence"],
    "500.5": ["Then any unspent mana left in a player"],
    "502.3": ["Then they untap them all simultaneously."],
    "504.1": ["First, the active player draws a card."],
    "508.1a": ["each one must either have haste or have been controlled by the active player continuously since the turn began"],
    "508.1f": ["The active player taps the chosen creatures."],
    "508.8": ["skip the declare blockers and combat damage steps"],
    "509.1a": ["The chosen creatures must be untapped"],
    "510.1c": ["it assigns its combat damage to those creatures divided as its controller chooses among them"],
    "510.2": ["is dealt simultaneously"],
    "510.4": ["the only creatures that assign combat damage in that step are those with first strike or double strike"],
    "514.1": ["they discard enough cards to reduce their hand size to that number"],
    "514.2": ["all damage marked on permanents (including phased-out permanents) is removed"],
    "601.2": ["To cast a spell is to take it from where it is (usually the hand), put it on the stack, and pay its costs"],
    "601.2a": ["a player first moves that card (or that copy of a card) from where it is to the stack"],
    "601.2c": ["The player announces their choice of an appropriate object or player for each target the spell requires."],
    "601.2g": ["Mana abilities must be activated before costs are paid."],
    "601.2h": ["Partial payments are not allowed."],
    "601.2i": ["then the spell becomes cast"],
    "605.3a": ["A player may activate an activated mana ability whenever they have priority"],
    "608.2b": ["no longer in the zone it was in when it was targeted is illegal"],
    "608.2n": ["As the final part of an instant or sorcery spell"],
    "608.3a": ["it becomes a permanent and enters the battlefield under the control of the spell"],
    "701.6a": ["A countered spell is put into its owner"],
    "702.7b": ["the only creatures that assign combat damage in that step are those with first strike or double strike"],
    "702.9b": ["except by creatures with flying and/or reach"],
    "702.10b": ["If a creature has haste, it can attack even if it hasn"],
    "702.20b": ["cause creatures with vigilance to tap"],
    "704.5a": ["If a player has 0 or less life, that player loses the game."],
    "704.5b": ["attempted to draw a card from a library with no cards in it since the last time state-based actions were checked"],
    "704.5f": ["If a creature has toughness 0 or less"],
    "704.5g": ["that creature has been dealt lethal damage and is destroyed"],
    "733.1": ["the entire action is reversed and any payments already made are canceled",
              "If the action was casting a spell, the spell returns to the zone it came from.",
              "Each player may also reverse any legal mana abilities that player activated while making the illegal play"],
    "733.2": ["the player who had priority retains it"],
    "119.3": ["If an effect causes a player to gain life or lose life, that player’s life total is adjusted accordingly."],
    "115.1": ["Some spells and abilities require their controller to choose one or more targets for them."],
    "120.3": ["Damage may have one or more of the following results"],
    "120.3a": ["Damage dealt to a player by a source without infect causes that player to lose that much life."],
    "205.3k": ["The spell types are Adventure, Arcane, Lesson, Omen, and Trap."],
}
