# -*- coding: utf-8 -*-
"""data/stub_decks.py — Real + hardcoded stub decklists.
Auto-generated by build_stubs.py.
"""

_DB_DECKS = {
    # Boros Energy (modern)
    "boros_energy": {"format": "modern", "mainboard": {"Ajani, Nacatl Pariah": 4, "Arena of Glory": 3, "Arid Mesa": 4, "Elegant Parlor": 2, "Flooded Strand": 4, "Galvanic Discharge": 4, "Goblin Bombardment": 3, "Guide of Souls": 4, "Marsh Flats": 2, "Mountain": 1, "Ocelot Pride": 4, "Phlage, Titan of Fire's Fury": 4, "Plains": 2, "Ragavan, Nimble Pilferer": 4, "Sacred Foundry": 3, "Seasoned Pyromancer": 3, "Static Prison": 3, "Thraben Charm": 2, "Voice of Victory": 3, "Windswept Heath": 1}},
    # uw blink (Gauntlet A) (modern)
    "uw_blink": {"format": "modern", "mainboard": {"Flooded Strand": 2, "Phelia, Exuberant Shepherd": 4, "Witch Enchanter": 4, "Arid Mesa": 2, "Sanctifier en-Vec": 1, "Flagstones of Trokair": 4, "Ephemerate": 4, "Mockingbird": 1, "Hallowed Fountain": 3, "Guide of Souls": 4, "Consign to Memory": 1, "White Orchid Phantom": 4, "Meticulous Archive": 3, "Ocelot Pride": 4, "Prismatic Ending": 2, "Starfield Shepherd": 3, "Plains": 3, "Solitude": 4, "Rest in Peace": 1, "Marsh Flats": 2, "Quantum Riddler": 4}},
    # belcher (Gauntlet B) (modern)
    "belcher": {"format": "modern", "mainboard": {"Suppression Ray": 4, "Sea Gate Restoration": 4, "Flare of Denial": 2, "Whir of Invention": 4, "Fallaji Archaeologist": 4, "Disrupting Shoal": 4, "Force of Negation": 2, "Thundertrap Trainer": 4, "Strix Serenade": 1, "Into the Flood Maw": 1, "Stern Scolding": 2, "Lotus Bloom": 4, "Jwari Disruption": 4, "Beyeen Veil": 1, "Goblin Charbelcher": 4, "Hydroelectric Specimen": 4, "Sink into Stupor": 4, "Waterlogged Teachings": 3, "Tameshi, Reality Architect": 4}},
    # esper mid (Gauntlet C) (modern)
    "esper_mid": {"format": "modern", "mainboard": {"Swamp": 1, "Flickerwisp": 3, "Phelia, Exuberant Shepherd": 4, "Flooded Strand": 4, "Witch Enchanter": 4, "Thoughtseize": 4, "Fatal Push": 4, "Ephemerate": 3, "Inquisition of Kozilek": 1, "Hallowed Fountain": 1, "Teferi, Time Raveler": 1, "Polluted Delta": 1, "Undercity Sewers": 1, "White Orchid Phantom": 2, "Shadowy Backstreet": 1, "Meticulous Archive": 1, "Watery Grave": 1, "Emperor of Bones": 3, "Solitude": 4, "Plains": 2, "Boggart Trawler": 1, "Godless Shrine": 2, "Quantum Riddler": 3, "Marsh Flats": 4, "Overlord of the Balemurk": 4}},
    # prowess (Gauntlet D) (modern)
    "prowess": {"format": "modern", "mainboard": {"Dragon's Rage Channeler": 4, "Thundering Falls": 1, "Expressive Iteration": 4, "Arid Mesa": 2, "Lightning Bolt": 4, "Preordain": 4, "Scalding Tarn": 2, "Mutagenic Growth": 4, "Mountain": 3, "Wooded Foothills": 2, "Cori-Steel Cutter": 4, "Mishra's Bauble": 4, "Steam Vents": 3, "Violent Urge": 2, "Monastery Swiftspear": 4, "Fiery Islet": 2, "Bloodstained Mire": 3, "Slickshot Show-Off": 4, "Lava Dart": 4}},
    # control (Gauntlet E) (modern)
    "control": {"format": "modern", "mainboard": {"Thundering Falls": 1, "Hall of Storm Giants": 1, "Otawara, Soaring City": 1, "Flooded Strand": 4, "Counterspell": 2, "Monumental Henge": 1, "Arid Mesa": 2, "Hallowed Fountain": 2, "Scalding Tarn": 1, "Orim's Chant": 4, "Force of Negation": 2, "Consult the Star Charts": 2, "Island": 2, "Isochron Scepter": 1, "Teferi, Time Raveler": 4, "Spell Snare": 2, "Polluted Delta": 1, "Mystic Gate": 1, "Narset, Parter of Veils": 4, "Stern Scolding": 1, "Meticulous Archive": 2, "Subtlety": 1, "Day's Undoing": 2, "Prismatic Ending": 3, "Stock Up": 1, "Solitude": 4, "Lorien Revealed": 2, "Plains": 2, "Supreme Verdict": 2, "Steam Vents": 1, "Geier Reach Sanitarium": 1}},
    # esper vengance (Gauntlet F) (modern)
    "esper_vengance": {"format": "modern", "mainboard": {"Faithful Mending": 3, "Swamp": 1, "Goryo's Vengeance": 4, "Thoughtseize": 2, "Flooded Strand": 4, "Griselbrand": 1, "Tainted Indulgence": 1, "Ephemerate": 4, "Preordain": 1, "Hallowed Fountain": 1, "Breeding Pool": 1, "Consign to Memory": 1, "Island": 1, "Force of Negation": 3, "Atraxa, Grand Unifier": 4, "Undercity Sewers": 1, "Psychic Frog": 4, "Shadowy Backstreet": 1, "Meticulous Archive": 1, "Polluted Delta": 4, "Watery Grave": 1, "Prismatic Ending": 3, "Solitude": 4, "Plains": 1, "Godless Shrine": 1, "Marsh Flats": 3, "Quantum Riddler": 4}},
    # esper blink (Gauntlet G) (modern)
    "esper_blink": {"format": "modern", "mainboard": {"Swamp": 1, "Phelia, Exuberant Shepherd": 4, "Flooded Strand": 4, "Ephemerate": 2, "Fatal Push": 4, "Hallowed Fountain": 1, "Teferi, Time Raveler": 2, "Force of Negation": 4, "Island": 1, "Consign to Memory": 3, "Psychic Frog": 4, "Shadowy Backstreet": 1, "Meticulous Archive": 1, "Polluted Delta": 4, "Watery Grave": 1, "Emperor of Bones": 2, "Subtlety": 4, "Hydroelectric Specimen": 3, "Plains": 1, "Godless Shrine": 1, "Quantum Riddler": 4, "Overlord of the Balemurk": 4, "Marsh Flats": 4}},
    # neoform (Gauntlet I) (modern)
    "neoform": {"format": "modern", "mainboard": {"Allosaurus Rider": 4, "Disciple of Freyalise": 2, "Generous Ent": 2, "Ghalta, Stampede Tyrant": 2, "Atraxa, Grand Unifier": 1, "Endurance": 1, "Griselbrand": 1, "Hooting Mandrills": 1, "Xenagos, God of Revels": 1, "Consign to Memory": 4, "Pact of Negation": 4, "Planar Genesis": 4, "Summoner's Pact": 4, "Veil of Summer": 4, "Eldritch Evolution": 4, "Neoform": 4, "Bridgeworks Battle": 2, "Misty Rainforest": 4, "Hedge Maze": 3, "Flooded Strand": 2, "Scalding Tarn": 2, "Boseiju, Who Endures": 1, "Breeding Pool": 1, "Forest": 1, "Island": 1}},
    # titan (Gauntlet J) (modern)
    "titan": {"format": "modern", "mainboard": {"Arboreal Grazer": 4, "Primeval Titan": 4, "Aftermath Analyst": 1, "Icetill Explorer": 1, "Amulet of Vigor": 4, "Summoner's Pact": 2, "Malevolent Rumble": 4, "Green Sun's Zenith": 3, "Scapeshift": 2, "Spelunking": 4, "Urza's Saga": 4, "Crumbling Vestige": 4, "Boseiju, Who Endures": 3, "Simic Growth Chamber": 3, "Gruul Turf": 2, "Lotus Field": 2, "Snow-Covered Forest": 2, "Echoing Deeps": 1, "Forest": 1, "Ghost Quarter": 1, "Hanweir Battlements": 1, "Mirrorpool": 1, "Otawara, Soaring City": 1, "Selesnya Sanctuary": 1, "Shifting Woodland": 1, "Tolaria West": 1, "Urza's Cave": 1, "Vesuva": 1}},
    # etron (Gauntlet K) (modern)
    "etron": {"format": "modern", "mainboard": {"Devourer of Destiny": 4, "Thought-Knot Seer": 4, "Glaring Fleshraker": 2, "Sire of Seven Deaths": 2, "Expedition Map": 4, "Mind Stone": 4, "Chalice of the Void": 1, "Relic of Progenitus": 1, "Vexing Bauble": 1, "Kozilek's Command": 4, "Dismember": 2, "Warping Wail": 1, "All Is Dust": 1, "Karn, the Great Creator": 4, "Ugin, Eye of the Storms": 3, "Eldrazi Temple": 4, "Ugin's Labyrinth": 4, "Urza's Mine": 4, "Urza's Power Plant": 4, "Urza's Tower": 4, "Swamp": 1, "Wastes": 1}},
    # domain (Gauntlet L) (modern)
    "domain": {"format": "modern", "mainboard": {"Phlage, Titan of Fire's Fury": 4, "Ragavan, Nimble Pilferer": 4, "Scion of Draco": 4, "Territorial Kavu": 4, "Fable of the Mirror-Breaker": 3, "Lightning Bolt": 4, "Stubborn Denial": 3, "Consign to Memory": 2, "Prismatic Ending": 2, "Leyline Binding": 4, "Leyline of the Guildpact": 4, "Arid Mesa": 4, "Flooded Strand": 4, "Wooded Foothills": 4, "Arena of Glory": 2, "Steam Vents": 2, "Godless Shrine": 1, "Indatha Triome": 1, "Lush Portico": 1, "Mountain": 1, "Plains": 1, "Temple Garden": 1, "Thundering Falls": 1}},
    # Humana (legacy)
    "humans": {"format": "legacy", "mainboard": {"Adeline, Resplendent Cathar": 2, "Cavern of Souls": 4, "Champion of the Parish": 4, "Coppercoat Vanguard": 4, "Eiganjo, Seat of the Empire": 1, "Esper Sentinel": 4, "Guide of Souls": 4, "Karakas": 2, "Kytheon, Hero of Akros": 2, "Luminarch Aspirant": 1, "Mutavault": 2, "Plains": 6, "Swords to Plowshares": 4, "Thalia, Guardian of Thraben": 4, "Thalia's Lieutenant": 4, "Urdnan, Dromoka Warrior": 2, "Voice of Victory": 3, "Wasteland": 4, "Witch Enchanter": 1, "Zack Fair": 2}},
    # Extra stub: mono_red_aggro_standard
    "mono_red_aggro_standard": {"format": "standard", "mainboard": {"Monastery Swiftspear": 4, "Goblin Guide": 4, "Cacophony Scamp": 4, "Lightning Bolt": 4, "Slickshot Show-Off": 4, "Dragon's Rage Channeler": 4, "Lava Dart": 4, "Mutagenic Growth": 4, "Galvanic Discharge": 4, "Felonious Rage": 2, "Mountain": 16, "Arid Mesa": 4, "Bloodstained Mire": 2}},
    # Extra stub: izzet_phoenix
    "izzet_phoenix": {"format": "pioneer", "mainboard": {"Arclight Phoenix": 4, "Sprite Dragon": 4, "Dragon's Rage Channeler": 4, "Ledger Shredder": 4, "Consider": 4, "Fiery Impulse": 4, "Lightning Bolt": 4, "Strategic Planning": 4, "Expressive Iteration": 4, "Treasure Cruise": 2, "Steam Vents": 4, "Spirebluff Canal": 4, "Shivan Reef": 4, "Island": 3, "Mountain": 3, "Riverglide Pathway": 3}},
    # Extra stub: rakdos_midrange
    "rakdos_midrange": {"format": "pioneer", "mainboard": {"Thoughtseize": 4, "Fatal Push": 4, "Fable of the Mirror-Breaker": 4, "Graveyard Trespasser": 4, "Bloodtithe Harvester": 4, "Sheoldred, the Apocalypse": 3, "Invoke Despair": 3, "Dreadbore": 2, "Kolaghan's Command": 2, "Reckoner Bankbuster": 2, "Preordain": 2, "Blood Crypt": 4, "Blightstep Pathway": 4, "Haunted Ridge": 4, "Swamp": 3, "Mountain": 2, "Sulfurous Springs": 3}},
    # Extra stub: izzet_prowess_standard
    "izzet_prowess_standard": {"format": "standard", "mainboard": {"Monastery Swiftspear": 4, "Dragon's Rage Channeler": 4, "Slickshot Show-Off": 4, "Cori-Steel Cutter": 4, "Lightning Bolt": 4, "Lava Dart": 4, "Mishra's Bauble": 4, "Mutagenic Growth": 4, "Expressive Iteration": 4, "Steam Vents": 4, "Mountain": 6, "Island": 3, "Scalding Tarn": 4, "Bloodstained Mire": 3}},
    # Extra stub: dimir_midrange
    "dimir_midrange": {"format": "standard", "mainboard": {"Psychic Frog": 4, "Thoughtseize": 4, "Fatal Push": 4, "Overlord of the Balemurk": 4, "Raffine, Scheming Seer": 3, "Sheoldred, the Apocalypse": 2, "Consider": 4, "Preordain": 4, "Boggart Trawler": 2, "Emperor of Bones": 1, "Watery Grave": 4, "Underground River": 4, "Shadowy Backstreet": 2, "Swamp": 3, "Island": 2, "Flooded Strand": 4, "Polluted Delta": 3}},
    # Extra stub: 5c_humans
    "5c_humans": {"format": "pioneer", "mainboard": {"Champion of the Parish": 4, "Thalia's Lieutenant": 4, "Kitesail Freebooter": 4, "Mantis Rider": 4, "Reflector Mage": 4, "Mayor of Avabruck": 4, "Coppercoat Vanguard": 4, "General Kudro of Drannith": 3, "Cavern of Souls": 4, "Unclaimed Territory": 4, "Seachrome Coast": 4, "Sacred Foundry": 2, "Hallowed Fountain": 2, "Stomping Ground": 2, "Temple Garden": 2, "Plains": 3, "Forest": 2}},
}


def get_stub_deck_list(deck_name: str):
    import re
    key = deck_name.lower().replace(" ","_").replace("'","").replace("/","_").replace("-","_")
    key = re.sub(r"_\(gauntlet_\w+\)", "", key).strip("_")
    if key in _DB_DECKS: return _DB_DECKS[key]["mainboard"]
    for k, v in _DB_DECKS.items():
        if k == key or k.startswith(key) or key.startswith(k[:max(4,len(key)-4)]):
            return v["mainboard"]
    return None

def get_format_decks(fmt): return {k:v for k,v in _DB_DECKS.items() if v["format"]==fmt}
